# Numpy tutorial

NumPy — это библиотека языка Python, добавляющая поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых (и очень быстрых) математических функций для операций с этими массивами.

## Создание массивов

В NumPy существует много способов создать массив. Один из наиболее простых - создать массив из обычных списков или кортежей Python, используя функцию numpy.array():

In [1]:
import numpy as np
a = np.array([1, 2, 3])

print(a, type(a), sep = '\n\n', end = '\n\n')

[1 2 3]

<class 'numpy.ndarray'>



Можно переопределить тип в момент создания:

In [2]:
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
b = np.array([1, 2, 3], dtype = float)

print(a, type(a[0]), b, type(b[0]), sep = '\n', end = '\n\n')

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.complex128'>
[1. 2. 3.]
<class 'numpy.float64'>



Функция np.array() трансформирует вложенные последовательности в многомерные массивы. Тип элементов массива зависит от типа элементов исходной последовательности (но можно и переопределить его в момент создания).

In [3]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
print(b, end = '\n\n')

[[1.5 2.  3. ]
 [4.  5.  6. ]]



Функция eye() создаёт единичную матрицу (двумерный массив).
Функция zeros() создает массив из нулей, а функция ones() — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype:

In [3]:
a = np.zeros((2, 3))
b = np.ones((2, 3, 3), dtype = int)
c = np.eye(4)

print(a, b, c, sep = '\n\n', end = '\n\n')

[[0. 0. 0.]
 [0. 0. 0.]]

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), только вместо списков она возвращает массивы, и принимает не только целые значения

In [88]:
a = np.arange(10, 30, 5)
b = np.arange(0, 1, 0.1)
print(a, b, sep = '\n\n', end = '\n\n')

[10 15 20 25]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]



При использовании arange() с аргументами типа float, сложно быть уверенным в том, сколько элементов будет получено (из-за ограничения точности чисел с плавающей запятой). Поэтому, в таких случаях обычно лучше использовать функцию linspace(), которая вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов:

In [6]:
print(np.linspace(0, 2, 9), end = '\n\n')

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]



fromfunction() применяет функцию ко всем комбинациям индексов:

In [7]:
def f1(i, j):
    return 3 * i + j

print(np.fromfunction(f1, (3, 4)), end = '\n\n')

[[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]



# Базовые операции

Математические операции над массивами выполняются поэлементно. Создается новый массив, который заполняется результатами действия оператора. Для таких операций необходимо, чтобы массивы были одного размера.

In [7]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)

print( 
    #операции массива с массивами:
    a + b, 
    a - b,
    a * b,
    a / b, # При делении на 0 возвращается inf (бесконечность)
    a ** b,
    a % b, # При взятии остатка от деления на 0 возвращается 0
      
      #операции массив с числами:
    a + 2,
    a * 3,
    a / 2,
    a % 3,
    a ** 2,
    a < 30,
    sep = '\n\n', end = '\n\n')


[20 31 42 53]

[20 29 38 47]

[  0  30  80 150]

[        inf 30.         20.         16.66666667]

[     1     30   1600 125000]

[0 0 0 2]

[22 32 42 52]

[ 60  90 120 150]

[10. 15. 20. 25.]

[2 0 1 2]

[ 400  900 1600 2500]

[ True False False False]



/tmp/ipykernel_13954/2076188221.py:10: RuntimeWarning: divide by zero encountered in divide
  a / b, # При делении на 0 возвращается inf (бесконечность)
/tmp/ipykernel_13954/2076188221.py:12: RuntimeWarning: divide by zero encountered in remainder
  a % b, # При взятии остатка от деления на 0 возвращается 0


Существуют также функции над векторами, например, sin, cos, tan, maximum, minimum и др. Их список можно посмотреть по ссылке: https://numpy.org/doc/stable/reference/routines.math.html

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

In [86]:
a = np.arange(10) ** 3
print(a, a[1], a[3:7], sep = '\n\n', end = '\n\n')
a[3:7] = 8
print(a, a[:: -1], sep = '\n\n', end = '\n\n')

for i in a:
    print(round(i ** (1/3)))

print()

[  0   1   8  27  64 125 216 343 512 729]

1

[ 27  64 125 216]

[  0   1   8   8   8   8   8 343 512 729]

[729 512 343   8   8   8   8   8   1   0]

0
1
2
2
2
2
2
7
8
9



У многомерных массивов на каждую ось приходится один индекс.

In [83]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
               [20, 21, 22, 23],
               [30, 31, 32, 33],
               [40, 41, 42, 43]])
print(
    b[2,3],  
    b[(2,3)],
    b[2][3],
    b[:,2],  
    b[:2],  
    b[1:3,:],
    b[-1],  # Последняя строка. Эквивалентно b[-1,:]
    sep = '\n\n', end = '\n\n')

23

23

23

[ 2 12 22 32 42]

[[ 0  1  2  3]
 [10 11 12 13]]

[[10 11 12 13]
 [20 21 22 23]]

[40 41 42 43]



У массива есть форма (shape), определяемая числом элементов вдоль каждой оси:

In [82]:
print(a, a.shape, sep = '\n\n', end = '\n\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

(4, 5)



Форма массива может быть изменена с помощью различных команд:

In [81]:
a = np.arange(20)
a.shape = (4, 5) 
print(a, a.shape, a.ravel(), a.transpose(), a.reshape(2,10), sep = '\n\n', end = '\n\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

(4, 5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]



Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.
hstack() объединяет массивы по первым осям, vstack() — по последним:

In [93]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a, b, np.vstack((a, b)), np.hstack((a, b)), sep = '\n\n', end = '\n\n')

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



Функция column_stack() объединяет одномерные массивы в качестве столбцов двумерного массива:

In [95]:
print(np.column_stack((a, b)), end = '\n\n')

[[1 2 5 6]
 [3 4 7 8]]



Используя hsplit() вы можете разбить массив вдоль горизонтальной оси, указав либо число возвращаемых массивов одинаковой формы, либо номера столбцов, после которых массив разрезается "ножницами":

In [119]:
a = np.arange(12).reshape((2, 6))
print(a, np.hsplit(a, 3), np.hsplit(a, (3, 4)), sep = '\n\n', end = '\n\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]

[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]



## Копии и представления

При работе с массивами, их данные иногда необходимо копировать в другой массив, а иногда нет. Это часто является источником путаницы. Возможно 3 случая:

In [120]:
#Случай 1. Ссылочное присваивание.

a = np.arange(12)
b = a  # Нового объекта создано не было
print(b is a, end = '\n\n')  # a и b это два имени для одного и того же объекта ndarray
b.shape = (3,4)  # изменит форму a
print(a.shape, end = '\n\n')

True

(3, 4)



In [123]:
#Случай 2. Представление данных.
a = np.arange(12)
a.shape = (3, 4)

c = a.view()

print(c is a, end = '\n\n')
print(c.base is a, end = '\n\n')  # c это представление данных, принадлежащих a
c.shape = (2,6)  # форма а не поменяется
print(a.shape, end = '\n\n')
c[0,4] = 1234  # данные а изменятся
print(a, end = '\n\n')


#Срез массива это представление:
s = a[:,1:3]
s[:] = 10
print(a, end = '\n\n')

False

True

(3, 4)

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [127]:
#Случай 3. Полная копия.
a = np.arange(12)
a.shape = (3, 4)

d = a.copy()  # создается новый объект массива с новыми данными
print(d is a, end = '\n\n')
print(d.base is a, end = '\n\n')  # d не имеет ничего общего с а
d[0, 0] = 9999
print(a, d, sep = '\n\n', end = '\n\n')

False

False

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[9999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]

